// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {music} from '../models';
import {subtitles} from '../models';
import {torrent} from '../models';

export function AddVideoFile():Promise<database.MediaItem>;

export function DownloadSubtitle(arg1:string,arg2:string):Promise<string>;

export function GetConfigDir():Promise<string>;

export function GetLibraryItems(arg1:string,arg2:string):Promise<Array<database.MediaItem>>;

export function GetLibraryStats():Promise<database.GlobalStats>;

export function GetPlatform():Promise<string>;

export function GetRecentlyPlayed(arg1:number):Promise<Array<database.MediaItem>>;

export function GetWatchProgress(arg1:string):Promise<database.WatchProgress>;

export function MpvAddSubtitle(arg1:string):Promise<void>;

export function MpvGetDuration():Promise<number>;

export function MpvGetMediaInfo():Promise<Record<string, any>>;

export function MpvGetTimePosition():Promise<number>;

export function MpvGetTrackList():Promise<any>;

export function MpvPlayFile(arg1:string):Promise<void>;

export function MpvPlayURL(arg1:string,arg2:string):Promise<void>;

export function MpvPlayWithSubs(arg1:string,arg2:string):Promise<void>;

export function MpvScreenshot(arg1:string):Promise<void>;

export function MpvSeek(arg1:number):Promise<void>;

export function MpvSeekRelative(arg1:number):Promise<void>;

export function MpvSetAudioTrack(arg1:number):Promise<void>;

export function MpvSetPlaybackSpeed(arg1:number):Promise<void>;

export function MpvSetSubtitleTrack(arg1:number):Promise<void>;

export function MpvSetVolume(arg1:number):Promise<void>;

export function MpvStop():Promise<void>;

export function MpvToggleFullscreen():Promise<void>;

export function MpvTogglePause():Promise<void>;

export function MusicGetTrackInfo(arg1:string):Promise<music.TrackInfo>;

export function MusicPlay(arg1:string):Promise<void>;

export function MusicScanLibrary(arg1:string):Promise<Array<music.TrackInfo>>;

export function MusicSeek(arg1:number):Promise<void>;

export function MusicSetVolume(arg1:number):Promise<void>;

export function MusicStop():Promise<void>;

export function MusicTogglePause():Promise<void>;

export function OpenFilePicker():Promise<string>;

export function OpenFolderPicker():Promise<string>;

export function SaveWatchProgress(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ScanFolder():Promise<Array<database.MediaItem>>;

export function SearchSubtitles(arg1:string,arg2:string,arg3:number,arg4:number):Promise<Array<subtitles.SearchResult>>;

export function SearchSubtitlesByFile(arg1:string,arg2:string):Promise<Array<subtitles.SearchResult>>;

export function TorrentAddFile(arg1:string):Promise<torrent.TorrentInfo>;

export function TorrentAddMagnet(arg1:string):Promise<torrent.TorrentInfo>;

export function TorrentGetStatus(arg1:string):Promise<torrent.TorrentStatus>;

export function TorrentGetStreamURL(arg1:string,arg2:number):Promise<string>;

export function TorrentList():Promise<Array<torrent.TorrentInfo>>;

export function TorrentRemove(arg1:string):Promise<void>;
