// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadSubtitle(arg1, arg2) {
  return window['go']['main']['App']['DownloadSubtitle'](arg1, arg2);
}

export function GetConfigDir() {
  return window['go']['main']['App']['GetConfigDir']();
}

export function GetLibraryItems(arg1, arg2) {
  return window['go']['main']['App']['GetLibraryItems'](arg1, arg2);
}

export function GetLibraryStats() {
  return window['go']['main']['App']['GetLibraryStats']();
}

export function GetPlatform() {
  return window['go']['main']['App']['GetPlatform']();
}

export function MpvAddSubtitle(arg1) {
  return window['go']['main']['App']['MpvAddSubtitle'](arg1);
}

export function MpvGetDuration() {
  return window['go']['main']['App']['MpvGetDuration']();
}

export function MpvGetTimePosition() {
  return window['go']['main']['App']['MpvGetTimePosition']();
}

export function MpvGetTrackList() {
  return window['go']['main']['App']['MpvGetTrackList']();
}

export function MpvPlayFile(arg1) {
  return window['go']['main']['App']['MpvPlayFile'](arg1);
}

export function MpvPlayURL(arg1, arg2) {
  return window['go']['main']['App']['MpvPlayURL'](arg1, arg2);
}

export function MpvPlayWithSubs(arg1, arg2) {
  return window['go']['main']['App']['MpvPlayWithSubs'](arg1, arg2);
}

export function MpvScreenshot(arg1) {
  return window['go']['main']['App']['MpvScreenshot'](arg1);
}

export function MpvSeek(arg1) {
  return window['go']['main']['App']['MpvSeek'](arg1);
}

export function MpvSeekRelative(arg1) {
  return window['go']['main']['App']['MpvSeekRelative'](arg1);
}

export function MpvSetAudioTrack(arg1) {
  return window['go']['main']['App']['MpvSetAudioTrack'](arg1);
}

export function MpvSetPlaybackSpeed(arg1) {
  return window['go']['main']['App']['MpvSetPlaybackSpeed'](arg1);
}

export function MpvSetSubtitleTrack(arg1) {
  return window['go']['main']['App']['MpvSetSubtitleTrack'](arg1);
}

export function MpvSetVolume(arg1) {
  return window['go']['main']['App']['MpvSetVolume'](arg1);
}

export function MpvStop() {
  return window['go']['main']['App']['MpvStop']();
}

export function MpvToggleFullscreen() {
  return window['go']['main']['App']['MpvToggleFullscreen']();
}

export function MpvTogglePause() {
  return window['go']['main']['App']['MpvTogglePause']();
}

export function MusicGetTrackInfo(arg1) {
  return window['go']['main']['App']['MusicGetTrackInfo'](arg1);
}

export function MusicPlay(arg1) {
  return window['go']['main']['App']['MusicPlay'](arg1);
}

export function MusicScanLibrary(arg1) {
  return window['go']['main']['App']['MusicScanLibrary'](arg1);
}

export function MusicSeek(arg1) {
  return window['go']['main']['App']['MusicSeek'](arg1);
}

export function MusicSetVolume(arg1) {
  return window['go']['main']['App']['MusicSetVolume'](arg1);
}

export function MusicStop() {
  return window['go']['main']['App']['MusicStop']();
}

export function MusicTogglePause() {
  return window['go']['main']['App']['MusicTogglePause']();
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}

export function OpenFolderPicker() {
  return window['go']['main']['App']['OpenFolderPicker']();
}

export function ScanFolder() {
  return window['go']['main']['App']['ScanFolder']();
}

export function SearchSubtitles(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SearchSubtitles'](arg1, arg2, arg3, arg4);
}

export function SearchSubtitlesByFile(arg1, arg2) {
  return window['go']['main']['App']['SearchSubtitlesByFile'](arg1, arg2);
}

export function TorrentAddFile(arg1) {
  return window['go']['main']['App']['TorrentAddFile'](arg1);
}

export function TorrentAddMagnet(arg1) {
  return window['go']['main']['App']['TorrentAddMagnet'](arg1);
}

export function TorrentGetStatus(arg1) {
  return window['go']['main']['App']['TorrentGetStatus'](arg1);
}

export function TorrentGetStreamURL(arg1, arg2) {
  return window['go']['main']['App']['TorrentGetStreamURL'](arg1, arg2);
}

export function TorrentList() {
  return window['go']['main']['App']['TorrentList']();
}

export function TorrentRemove(arg1) {
  return window['go']['main']['App']['TorrentRemove'](arg1);
}
